### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by Zillaaa** [gonzoua/u-boot-pi#12]
Dear gonzoua,

my build has failed und -perhaps - this can be a makefile failure:
/home/andreas/Embedded_Linux/raspi/bootloader/u-boot-pi/include/linux/compiler-gcc.h:87:30: fatal error: linux/compiler-gcc5.h: file or folder not found 

Why he tries to load the file with "5" in it?

Thank you for your help!

**Comment by gonzoua** [comment]
This u-boot codebase is obsolete and no longer supported. All functionality is available in mainline u-boot in much cleaner and much more tested form. 

If for some reason you really need to use it, you can copy compiler-gcc5.h from mainline u-boot. compiler-gcc.h tries to determine gcc version and include respective header. When this repository was WIP I believe last stable version was gcc 4, since then gcc 5 was released but code wasn't updated:

https://github.com/gonzoua/u-boot-pi/blob/master/include/linux/compiler-gcc.h#L87
